/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package oodi.group1.items.ui;


import oodi.group1.items.db.ItemDao;
import oodi.group1.items.Item;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author chris
 */
public class NewItem extends javax.swing.JDialog {

    /**
     * Creates new form ItemManagement
     */
    public NewItem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField_itemUPC = new javax.swing.JTextField();
        jLabel_itemUPC = new javax.swing.JLabel();
        jTextField_itemName = new javax.swing.JTextField();
        jLabel_itemName = new javax.swing.JLabel();
        jTextField_unitPrice = new javax.swing.JTextField();
        jLabel_unitPrice = new javax.swing.JLabel();
        jTextField_manufacturer = new javax.swing.JTextField();
        jLabel_manufacturer = new javax.swing.JLabel();
        jLabel_category = new javax.swing.JLabel();
        jButton_submit = new javax.swing.JButton();
        jLabel_itemUnits = new javax.swing.JLabel();
        jTextField_itemUnits = new javax.swing.JTextField();
        jComboBox_category = new javax.swing.JComboBox<>();
        jLabel_Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Item");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTextField_itemUPC.setToolTipText("");
        jTextField_itemUPC.setName("UPC Text Field"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 20);
        getContentPane().add(jTextField_itemUPC, gridBagConstraints);

        jLabel_itemUPC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_itemUPC.setText("UPC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 10);
        getContentPane().add(jLabel_itemUPC, gridBagConstraints);

        jTextField_itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_itemNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 20);
        getContentPane().add(jTextField_itemName, gridBagConstraints);

        jLabel_itemName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_itemName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 10);
        getContentPane().add(jLabel_itemName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 20);
        getContentPane().add(jTextField_unitPrice, gridBagConstraints);

        jLabel_unitPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_unitPrice.setText("Unit Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 10);
        getContentPane().add(jLabel_unitPrice, gridBagConstraints);

        jTextField_manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_manufacturerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 20);
        getContentPane().add(jTextField_manufacturer, gridBagConstraints);

        jLabel_manufacturer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_manufacturer.setText("Manufacturer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 10);
        getContentPane().add(jLabel_manufacturer, gridBagConstraints);

        jLabel_category.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_category.setText("Category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 10);
        getContentPane().add(jLabel_category, gridBagConstraints);

        jButton_submit.setText("submit");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        getContentPane().add(jButton_submit, gridBagConstraints);

        jLabel_itemUnits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_itemUnits.setText("Units");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 10);
        getContentPane().add(jLabel_itemUnits, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 20);
        getContentPane().add(jTextField_itemUnits, gridBagConstraints);

        jComboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produce", "Bakery", "Snack", "Frozen", "Canned", "Drink", "Other" }));
        jComboBox_category.setMinimumSize(new java.awt.Dimension(64, 22));
        jComboBox_category.setPreferredSize(new java.awt.Dimension(64, 22));
        jComboBox_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 20);
        getContentPane().add(jComboBox_category, gridBagConstraints);

        jLabel_Title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Title.setText("CREATE NEW ITEM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel_Title, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_manufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_manufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_manufacturerActionPerformed

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        // TODO add your handling code here:
        String upc = jTextField_itemUPC.getText();
        String name = jTextField_itemName.getText();
        int units = Integer.parseInt(jTextField_itemUnits.getText());
        double unitPrice = Double.parseDouble(jTextField_unitPrice.getText());
        String manufacturer = jTextField_manufacturer.getText();
        String category = (String) jComboBox_category.getSelectedItem();

        Item newItem = new Item(upc, name, units, unitPrice, manufacturer, category);
        ItemDao.addItem(newItem);
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jTextField_itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_itemNameActionPerformed

    private void jComboBox_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewItem dialog = new NewItem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_submit;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_category;
    private javax.swing.JLabel jLabel_itemName;
    private javax.swing.JLabel jLabel_itemUPC;
    private javax.swing.JLabel jLabel_itemUnits;
    private javax.swing.JLabel jLabel_manufacturer;
    private javax.swing.JLabel jLabel_unitPrice;
    private javax.swing.JTextField jTextField_itemName;
    private javax.swing.JTextField jTextField_itemUPC;
    private javax.swing.JTextField jTextField_itemUnits;
    private javax.swing.JTextField jTextField_manufacturer;
    private javax.swing.JTextField jTextField_unitPrice;
    // End of variables declaration//GEN-END:variables
}
